kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false

prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/hostname: beachbumhq
    retention: 45d
    retentionSize: 8GiB
    scrapeInterval: 60s
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.<your_domain>.com
      serve_from_sub_path: false
  nodeSelector:
    kubernetes.io/hostname: beachbumhq
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: cf-prod
    hosts:
      - grafana.<your_domain>.com
    path: /
    tls:
      - hosts:
          - grafana.<your_domain>.com
        secretName: grafana-tls
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    storageClassName: local-path
    accessModes: ["ReadWriteOnce"]
    size: 2Gi
  service:
    type: ClusterIP

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/hostname: beachbumhq
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

kubeApiServer:
  serviceMonitor:
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: '(etcd_request_duration_seconds_bucket|apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_request_sli_duration_seconds_bucket|apiserver_response_sizes_bucket|apiserver_watch_cache_read_wait_seconds_bucket|apiserver_watch_list_duration_seconds_bucket|workqueue_queue_duration_seconds_bucket|workqueue_work_duration_seconds_bucket)'
        action: drop

kubelet:
  serviceMonitor:
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: '(etcd_.*_bucket|apiserver_.*_bucket|workqueue_.*_bucket|scheduler_.*_bucket)'
        action: drop
